In [2]:
import numpy as np
import pandas as pd
from math import exp

In [3]:
# sure working functions
def sigmoid(value):
    return 1.0/(1+exp(value * (-1)))

def sigma(arr_weight, arr_input, bias=0):
    #len(arr_weight) = len(arr_input)
    return arr_weight.dot(arr_input.transpose())[0] + bias

# hidden_layer = int (number of hidden layers)
# nb_nodes = arr[int] (number of nodes per hidden layer)
# len_input_matrix = int (number of features)
# Output: List of Matrixes
# Method: He initialization
# Link: https://towardsdatascience.com/weight-initialization-techniques-in-neural-networks-26c649eb3b78
def initialize_weights(hidden_layer, nb_nodes, len_input_matrix):
    arr_weights = list()
    for i in range(hidden_layer):
        if i==0:
            nb_nodes_prev = len_input_matrix
        else:
            nb_nodes_prev = nb_nodes[i-1]
        weight_matrix = np.random.randn(nb_nodes[i], nb_nodes_prev) * np.sqrt(2/(nb_nodes_prev+nb_nodes[i]))
        arr_weights.append(weight_matrix)
    return arr_weights

In [4]:
# functions in progress
def error(feed_forward_output, target_output):
    return 0.5*((target_output-feed_forward_output)**2)

def propagate_error_output_layer(feed_forward_output, target_output):
    return feed_forward_output*(1-feed_forward_output)*(target_output-feed_forward_output)

def propagate_error_hidden_layer_neuron(arr_weight_input, arr_neuron_input, arr_weight_output, arr_neuron_output):
    #Input here means input in a single neuron, while output means output of a single neuron
    #len(arr_weight) = len(arr_input)
    sigma_input, sigma_output = sigma(arr_weight_input, arr_neuron_input), sigma(arr_weight_output, arr_neuron_output)
    return sigmoid(sigma_input) * (1 - sigmoid(sigma_input)) * sigma_output

def update_weight_neuron(weight_prev_prev, weight_prev, nu, alfa, error, output_neuron):
    # weight_prev_prev = previous of weight_prev
    return weight_prev + weight_prev_prev * alfa + nu*error*output_neuron

In [46]:
# input_matrix = matrix[float] (data) (asumsi, kolom terakhir adalah hasil klasifikasi)
# hidden_layers = int (number of hidden layers)
# nb_nodes = arr[int] (number of nodes per hidden layer)
# nu = float (momentum)
# alfa = float (learning rate)
# epoch = int (number of training loops)
# batch_size = int (mini-batch)
def mini_batch_gradient_descent(input_matrix, hidden_layer, nb_nodes, nu, alfa, epoch, batch_size=1):
    
    #transpose-slicing, memisah input dan label
    col_width = input_matrix.shape[1]
    input_data = (input_matrix.transpose()[0:col_width-1]).transpose()
    label_data = (input_matrix.transpose()[col_width-1:col_width]).transpose()
    #print(input_data, "\n")
    #print(label_data, "\n")
    
    FFNN = initialize_weights(hidden_layer, nb_nodes, col_width-1)
    
    for i in range(len(epoch)):
        FFNN_prev = FFNN
        
    return output

In [43]:
# dataset load and preprocess
df = pd.read_csv("weather.csv")
#print(df.head, "\n")

# transform non-numeric data to numeric data (boolean type is already 0 and 1)
weather_dict = dict([("sunny",0), ("overcast",1), ("rainy",2)]) # bisa di automasi, tp terlanjur malas
label_dict = dict([("no",0), ("yes",1)])
newdf = df.replace({"outlook":weather_dict})
newdf = newdf.replace({"play":label_dict})
#print(newdf.head, "\n")

#scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() #feature_range=(0,1) (min_val, max_val)
scaler.fit(newdf)
data_matrix = scaler.transform(newdf) # di tahap ini, data sudah menjadi numpy array
#print(data_matrix, "\n")

#result = mini_batch_gradient_descent(data_matrix, 3, [2,3,4], 0.1 ,0.4, 2)

In [49]:
#playground

#print(np.random.randn(10,9) * np.sqrt(1/9))
#x = np.empty((3, 4))
#a = np.zeros( (3,4) )
#b = np.zeros( (2,3) )
#c = np.stack((x,a)) 
#np.concatenate((c, [a]))
#testarr = np.empty((3,4,5))

#emptyarr = list()
#a = np.random.randn(3, 5) * np.sqrt(2/(5+3))
#b = np.random.randn(5, 2) * np.sqrt(2/(5+2))
#emptyarr.append(a)
#emptyarr.append(b)
#print(emptyarr)

# main prog testing
hidden_layers = 3
nb_nodes = [3,4,2]


testarr = initialize_weights(3, [3,4,2], 5)
for i in range(len(testarr)):
    print(testarr[i], '\n')

[[ 0.72397728 -0.18787754  0.05099908 -0.30042582 -0.08220412]
 [-0.79028059 -0.0181332  -0.40216278  1.13272154 -0.74510839]
 [ 0.29529642 -0.45053729  0.16456503 -1.17169304 -0.34191728]] 

[[ 0.06600068 -0.83490396  0.73250927]
 [ 0.48718237  0.12585565 -0.03581342]
 [-0.89907174 -0.22755506  0.66923434]
 [ 0.23108605  0.21587736 -0.70941184]] 

[[-0.36974717  1.33856951 -0.14157714 -0.16977594]
 [ 0.91203602 -1.70103224  0.35850359 -1.04529694]] 

